namespace Unity.RichText
{
    [Flags]
    public enum UnityRichTextFlag
    {
        None,
        Bold,
        Italic,
        Align,
        AllCaps,
        Alpha,
        Lowercase,
        Uppercase,
        Nobr,
        NoParse,
        SRender,
        Strikethrough,
        Subscript,
        Superscript,
        Underline,
        Href,
        Size,
        Color,
        CSpace,
        Font,
        FontWeight,
        Gradient,
        Indent,
        LineHeight,
        LineIndent,
        Margin,
        Mark,
        MSpace,
        Pos,
        Rotate,
        Crossed,
        Space,
        Sprite,
        SmallCaps,
        Style,
        VOffset,
        Width
    }
}